# NOTE: update this with your service name
service: notes-app-api

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2
  profile: customer-account-dev
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    tableName: notes-app-api
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    stripeSecretKey: ${env:STRIPE_SECRET_KEY}

functions:
  create:
    handler: create.main
    role: NotesAppRole
    events:
      - http:
          path: notes
          method: post
          cors: true
          authorizer: aws_iam
  get:
    handler: get.main
    role: NotesAppRole
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true
          authorizer: aws_iam
  list:
    handler: list.main
    role: NotesAppRole
    events:
      - http:
          path: notes
          method: get
          cors: true
          authorizer: aws_iam
  update:
    handler: update.main
    role: NotesAppRole
    events:
      - http:
          path: notes/{id}
          method: put
          cors: true
          authorizer: aws_iam
  delete:
    handler: delete.main
    role: NotesAppRole
    events:
      - http:
          path: notes/{id}
          method: delete
          cors: true
          authorizer: aws_iam
  billing:
    handler: billing.main
    role: NotesAppRole
    events:
      - http:
          path: billing
          method: post
          cors: true
          authorizer: aws_iam
resources:
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/role.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/dynamodb-table.yml)}